spring:
  application:
    name: vehicle-verification-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/verification_db}
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD:apppassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

server:
  port: 8080
